#
#  $Id: Makefile.skel,v 1.1 2008-01-05 13:13:50 debug Exp $
#
#  Makefile for GXemul src/main/actions
#

CFLAGS=$(CWARNINGS) $(COPTIM) $(XINCLUDE) $(INCLUDE2)
LIBS=$(XLIB) $(OTHERLIBS)

OBJS=AddComponentAction.o RemoveComponentAction.o

all: $(OBJS)

$(OBJS): Makefile

clean:
	rm -f $(OBJS)

clean_all: clean
	rm -f Makefile

