#
#  $Id: Makefile.skel,v 1.112 2007-12-13 12:30:09 debug Exp $
#
#  Makefile for GXemul src
#

CFLAGS=$(CWARNINGS) $(COPTIM) $(XINCLUDE) $(INCLUDE)

all: do_gui do_main

do_gui:
	cd gui; $(MAKE); cd ..

do_main:
	cd main; $(MAKE); cd ..

clean:
	cd gui; $(MAKE) clean; cd ..
	cd main; $(MAKE) clean; cd ..

clean_all: clean
	cd gui; $(MAKE) clean_all; cd ..
	cd main; $(MAKE) clean_all; cd ..
	rm -f Makefile

