#
#  Makefile for GXmvcf
#

all:
	cd src; $(MAKE)

documentation:
	$(DOXYGEN) doc/Doxyfile

install:
	@echo TODO

clean:
	rm -rf doc/doxygen
	cd src; $(MAKE) clean

clean_all: clean
	rm -f _unittests.tmp unittest.h unittest_h.h
	rm -f config.h Makefile src/Makefile

