#
#  $Id: Makefile.skel,v 1.4 2007-12-18 14:07:52 debug Exp $
#
#  Makefile for GXemul src/gui
#

CFLAGS=$(CWARNINGS) $(COPTIM) $(XINCLUDE) $(INCLUDE1)

OBJS=DebugConsoleWidget.o EmulationDesignArea.o GXemulWindow.o

all: $(OBJS)

$(OBJS): Makefile

clean:
	rm -f $(OBJS) *core

clean_all: clean
	rm -f Makefile

