#
#  $Id: Makefile.skel,v 1.3 2007-12-13 23:22:05 debug Exp $
#
#  Makefile for GXemul src/gui
#

CFLAGS=$(CWARNINGS) $(COPTIM) $(XINCLUDE) $(INCLUDE)

OBJS=DebugConsoleWidget.o EmulationDesignArea.o GXemulWindow.o

all: $(OBJS)

$(OBJS): Makefile

clean:
	rm -f $(OBJS) *core

clean_all: clean
	rm -f Makefile

