#
#  $Id: Makefile.skel,v 1.2 2007-12-18 14:07:52 debug Exp $
#
#  Makefile for GXemul src/components
#

CFLAGS=$(CWARNINGS) $(COPTIM) $(XINCLUDE) $(INCLUDE1)

all: do_dummy

do_dummy:
	cd dummy; $(MAKE); cd ..

clean:
	cd dummy; $(MAKE) clean; cd ..

clean_all: clean
	cd dummy; $(MAKE) clean_all; cd ..
	rm -f Makefile

