#
#  $Id: Makefile.skel,v 1.6 2007-12-13 11:49:37 debug Exp $
#
#  Makefile for GXemul src/file
#

CFLAGS=$(CWARNINGS) $(COPTIM) $(XINCLUDE) $(DINCLUDE)

OBJS=file.o

all: $(OBJS)

$(OBJS): Makefile

file.o: file.cc file_aout.cc file_ecoff.cc file_elf.cc file_macho.cc \
	file_raw.cc file_srec.cc


clean:
	rm -f $(OBJS) *core

clean_all: clean
	rm -f Makefile

