#
#  $Id: Makefile.skel,v 1.6 2007-12-09 15:16:09 debug Exp $
#
#  Makefile for GXemul src/debugger
#

CFLAGS=$(CWARNINGS) $(COPTIM) $(XINCLUDE) $(DINCLUDE)

OBJS=debugger.o debugger_expr.o

all: $(OBJS)

$(OBJS): Makefile

debugger.cc: debugger_cmds.cc

clean:
	rm -f $(OBJS) *core

clean_all: clean
	rm -f Makefile

