#
#  $Id: Makefile.skel,v 1.2 2008-01-02 12:39:13 debug Exp $
#
#  Makefile for GXemul src/main/commands
#

CFLAGS=$(CWARNINGS) $(COPTIM) $(XINCLUDE) $(INCLUDE2)
LIBS=$(XLIB) $(OTHERLIBS)

OBJS=QuitCommand.o VersionCommand.o

all: $(OBJS)

$(OBJS): Makefile

clean:
	rm -f $(OBJS)

clean_all: clean
	rm -f Makefile

