#
#  $Id: Makefile.skel,v 1.4 2008-01-12 08:29:56 debug Exp $
#
#  Makefile for GXemul src/main/commands
#

CFLAGS=$(CWARNINGS) $(COPTIM) $(XINCLUDE) $(INCLUDE2)
LIBS=$(XLIB) $(OTHERLIBS)

OBJS=AddComponentCommand.o CloseCommand.o HelpCommand.o LoadCommand.o \
	QuitCommand.o RedoCommand.o RemoveComponentCommand.o \
	SaveCommand.o StatusCommand.o TreeCommand.o UndoCommand.o \
	VersionCommand.o

all: $(OBJS)

$(OBJS): Makefile

clean:
	rm -f $(OBJS)

clean_all: clean
	rm -f Makefile

