#
#  Makefile for GXmvcf.
#

CXXFLAGS=$(CXXFLAGSBASE) $(CPEDANTIC) $(INCLUDE1)
LIBS=$(XLIB) $(OTHERLIBS)

OBJS=debug_new.o UnitTest.o

all: $(OBJS)

$(OBJS): Makefile

runtests: main.o $(OBJS)
	$(CXX) $(CXXFLAGS) $(LIBS) main.o $(OBJS) -o runtests
	./runtests

clean:
	rm -f $(OBJS) runtests *core _test

clean_all: clean
	rm -f Makefile

