#
#  $Id: Makefile.skel,v 1.11 2007-12-29 16:18:51 debug Exp $
#
#  Makefile for GXemul src/main
#

CFLAGS=$(CWARNINGS) $(COPTIM) $(XINCLUDE) $(INCLUDE1)
LIBS=$(XLIB) $(OTHERLIBS)

OBJS=Action.o ActionStack.o Checksum.o \
	CommandInterpreter.o Component.o \
	debug_new.o EscapedString.o GXemul.o \
	StateVariable.o StateVariableValue.o UnitTest.o

all: $(OBJS)

$(OBJS): Makefile

clean:
	rm -f $(OBJS) *core _test

clean_all: clean
	rm -f Makefile

