#
#  $Id: Makefile.skel,v 1.8 2007-12-18 14:07:52 debug Exp $
#
#  Makefile for GXemul src/main
#

CFLAGS=$(CWARNINGS) $(COPTIM) $(XINCLUDE) $(INCLUDE1)
LIBS=$(XLIB) $(OTHERLIBS)

OBJS=Action.o ActionStack.o Component.o ConfigNode.o \
	debug_new.o GXemul.o TTYDebugConsole.o UnitTest.o

all: $(OBJS)

$(OBJS): Makefile

clean:
	rm -f $(OBJS) *core _test

clean_all: clean
	rm -f Makefile

